### ISSUE TITLE
Provide basic example.

### ISSUE THREAD

**Issue by desert** [4yopping/node-odoo#1]
There is no hello-world, 

I tried using this example but i get Session 

```
var odoo = require('node-odoo');

var erp = new odoo({
    host:'xxx.xxxxxx.xxxx',
    port: 8069,
    database: 'MYDB',
    username: 'xxxxxxx',
    password: 'xxxxxxxxxx'
});

erp.connect(function(err, res){
  if (err){
    console.log("Error logging in ", err);
    return
  }
  console.log("Connect callback", res)    
  erp.get('res.partner', 4, function(err, res){
  if (err)
    console.log("Error search ", err);
  else 
    console.log("Search callback", res)    
  })
})
```

But i got SessionExpiredException
```
Error search  { message: 'OpenERP WebClient Error',                                                                                                                                     
  code: 300,                                                                                                                                                                            
  data:                                                                                                                                                                                 
   { debug: 'Client Traceback (most recent call last):\n  File "/opt/openerp7-trunk/web/addons/web/http.py", line 204, in dispatch\n    response["result"] = method(self, **self.params)\n  File "/opt/openerp7-trunk/web/addons/web/controllers/main.py", line 1124, in call\n    return self._call_kw(req, model, method, args, {})\n  File "/opt/openerp7-trunk/web/addons/web/controllers/main.py", line 1120, in _call_kw\n    return getattr(req.session.model(model), method)(*args, **kwargs)\n  File "/opt/openerp7-trunk/web/addons/web/session.py", line 158, in model\n    raise SessionExpiredException("Session expired")\nSessionExpiredException: Session expired\n',                                                                           
     type: 'client_exception' } }
```

**Comment by markotom** [comment]
This is a basic example that works: 

```js
var Odoo = require('node-odoo');

var odoo = new Odoo({
  host: 'localhost',
  port: 4569,
  database: '4yopping',
  username: 'admin',
  password: '4yopping'
});

// Connect to Odoo
odoo.connect(function (err) {
  if (err) { return console.log(err); }

  // Get a partner
  odoo.get('res.partner', 4, function (err, partner) {
    if (err) { return console.log(err); }

    console.log('Partner', partner);
  });
});
```

Should returns something like this:

```
{
  ean13: false,
  property_account_position: false,
  signup_valid: false,
  ref_companies: [],
  sale_order_count: 0,
  purchase_order_count: 0,
  write_uid: [ 1, 'Administrator' ],
  contact_address: '\n\n  \n',
  property_stock_customer: [ 9, 'Partner Locations/Customers' ],
  property_product_pricelist: [ 1, 'Public Pricelist (EUR)' ],
  signup_url: false,
  journal_item_count: 0,
  parent_name: false,
  display_name: 'Public user',
  opt_out: false,
  title: false,
  company_id: [ 1, 'YourCompany' ],
  parent_id: false,
  last_reconciliation_date: false,
  contracts_count: 0,
  employee: false,
  ...
}
```

Do you have verified that your user has permission to read from Odoo panel?

**Comment by Quantium** [comment]
I've closed the issue because this example works fine for me and with other test environment. @desert, Can you tell us if now you can actually connect to you Odoo server please?

Remember, as @markotom said: Please verify if the user you're using to connect to Odoo has the right permissions.

**Comment by jamshu** [comment]
This Works for all User Except Admin User ...Why it not works for admin?
